fix: unping draft-button dependency in zen-title-block
Once I upgraded, I was getting weird type errors

```
draft-packages/title-block-zen/KaizenDraft/TitleBlockZen/SecondaryActions.tsx:85:16 - error TS2322: Type '{
"data-automation-id": string;
icon?: SVGAttributes<SVGSymbolElement> | undefined;
form?: boolean | undefined;
label: string;
id?: string | undefined;
destructive?: boolean | undefined;
disabled?: boolean | undefined;
reversed: boolean;
href?: string | undefined;
newTabAndIUnderstandTheAccessibilityImplications?: boolean | undefined;
type?: "button" | "submit" | "reset" | undefined;
fullWidth?: boolean | undefined;
disableTabFocusAndIUnderstandTheAccessibilityImplications?: boolean | undefined;
onFocus?: ((e: FocusEvent<HTMLElement>) => void) | undefined;
onBlur?: ((e: FocusEvent<HTMLElement>) => void) | undefined;
iconPosition?: "start" | "end" | undefined;
primary?: boolean | undefined;
secondary: boolean;
reverseColor?: "peach" | "seedling" | "wisteria" | "yuzu" | "cluny" | undefined;
component?: ComponentClass<CustomButtonProps, any> | FunctionComponent<CustomButtonProps> | undefined;
onMouseDown?: ((e: MouseEvent<Element, MouseEvent>) => void) | undefined;
working?: boolean | undefined;
workingLabel?: string | undefined;
} | { "data-automation-id": string;
icon?: SVGAttributes<SVGSymbolElement> | undefined;
form?: boolean | undefined;
label: string;
id?: string | undefined;
destructive?: boolean | undefined;
disabled?: boolean | undefined;
reversed: boolean;
onClick?: ((e: any) => void) | undefined;
newTabAndIUnderstandTheAccessibilityImplications?: boolean | undefined;
type?: "button" | "submit" | "reset" | undefined;
fullWidth?: boolean | undefined;
disableTabFocusAndIUnderstandTheAccessibilityImplications?: boolean | undefined;
onFocus?: ((e: FocusEvent<HTMLElement>) => void) | undefined;
onBlur?: ((e: FocusEvent<HTMLElement>) => void) | undefined;
iconPosition?: "start" | "end" | undefined;
primary?: boolean | undefined;
secondary: boolean;
reverseColor?: "peach" | "seedling" | "wisteria" | "yuzu" | "cluny" | undefined;
component?: ComponentClass<CustomButtonProps, any> | FunctionComponent<CustomButtonProps> | undefined;
onMouseDown?: ((e: MouseEvent<Element, MouseEvent>) => void) | undefined;
working?: boolean | undefined;
workingLabel?: string | undefined;
}' is not assignable to type '(IntrinsicAttributes & GenericProps & LabelPropsGeneric & WorkingUndefinedProps & RefAttributes<ButtonRef | undefined>) | (IntrinsicAttributes & GenericProps & LabelPropsGeneric & WorkingProps & RefAttributes<ButtonRef | undefined>)'.
  Type '{ "data-automation-id": string;
  icon?: SVGAttributes<SVGSymbolElement> | undefined;
  form?: boolean | undefined;
  label: string;
  id?: string | undefined;
  destructive?: boolean | undefined;
  disabled?: boolean | undefined;
  reversed: boolean;
  href?: string | undefined;
  newTabAndIUnderstandTheAccessibilityImplications?: boolean | undefined;
  type?: "button" | "submit" | "reset" | undefined;
  fullWidth?: boolean | undefined;
  disableTabFocusAndIUnderstandTheAccessibilityImplications?: boolean | undefined;
  onFocus?: ((e: FocusEvent<HTMLElement>) => void) | undefined;
  onBlur?: ((e: FocusEvent<HTMLElement>) => void) | undefined;
  iconPosition?: "start" | "end" | undefined;
  primary?: boolean | undefined;
  secondary: boolean;
  reverseColor?: "peach" | "seedling" | "wisteria" | "yuzu" | "cluny" | undefined;
  component?: ComponentClass<CustomButtonProps, any> | FunctionComponent<CustomButtonProps> | undefined;
  onMouseDown?: ((e: MouseEvent<Element, MouseEvent>) => void) | undefined;
  working?: boolean | undefined;
  workingLabel?: string | undefined;
  }' is not assignable to type '(IntrinsicAttributes & GenericProps & LabelPropsGeneric & WorkingUndefinedProps & RefAttributes<ButtonRef | undefined>) | (IntrinsicAttributes & GenericProps & LabelPropsGeneric & WorkingProps & RefAttributes<ButtonRef | undefined>)'.
    Type '{ "data-automation-id": string;
    icon?: SVGAttributes<SVGSymbolElement> | undefined;
    form?: boolean | undefined;
    label: string;
    id?: string | undefined;
    destructive?: boolean | undefined;
    disabled?: boolean | undefined;
    reversed: boolean;
    href?: string | undefined;
    newTabAndIUnderstandTheAccessibilityImplications?: boolean | undefined;
    type?: "button" | "submit" | "reset" | undefined;
    fullWidth?: boolean | undefined;
    disableTabFocusAndIUnderstandTheAccessibilityImplications?: boolean | undefined;
    onFocus?: ((e: FocusEvent<HTMLElement>) => void) | undefined;
    onBlur?: ((e: FocusEvent<HTMLElement>) => void) | undefined;
    iconPosition?: "start" | "end" | undefined;
    primary?: boolean | undefined;
    secondary: boolean;
    reverseColor?: "peach" | "seedling" | "wisteria" | "yuzu" | "cluny" | undefined;
    component?: ComponentClass<CustomButtonProps, any> | FunctionComponent<CustomButtonProps> | undefined;
    onMouseDown?: ((e: MouseEvent<Element, MouseEvent>) => void) | undefined;
    working?: boolean | undefined;
    workingLabel?: string | undefined;
    }' is not assignable to type 'WorkingProps'.
      Types of property 'working' are incompatible.
        Type 'boolean | undefined' is not assignable to type 'boolean'.
          Type 'undefined' is not assignable to type 'boolean'.
```

I've worked around this by loosening the button types so that we no longer use a union of "WorkingProps" and "WorkingUndefinedProps" but rather allow each of the props to be defined or not separately.

I hope we get a better solution, but I'm doing this to unblock a local build.